### ISSUE TITLE
upgrade to ocaml 5.1.1

### ISSUE THREAD

**Issue by nlsandler** [nlsandler/nqcc2#3]
Building w/ latest ocaml currently fails with:
```
File "lib/cfg.ml", line 244, characters 6-24:
244 |       Format.pp_open_tag out "table";
            ^^^^^^^^^^^^^^^^^^
Error: Unbound value Format.pp_open_tag
```

It looks like the latest `BatFormat` has neither `pp_open_tag` nor `pp_open_stag`.

One possible fix is to use non-batteries `Format` module in cfg.ml, but I may want to just not use batteries at all.

**Comment by cwt8805** [comment]
I'm not familiar with OCaml. Can you directly update the source code for the latest version of OCaml?

**Comment by nlsandler** [comment]
The latest `main` does not use batteries, and builds with OCaml version 5.2.0.
